In [34]:
from google.colab import files
file=files.upload()

Saving startup_funding.csv to startup_funding (1).csv

In [35]:
import pandas as pd
df = pd.read_csv("startup_funding.csv")
df.head()
#displaying first 5 rows

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09-01-2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13-01-2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09-01-2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02-01-2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02-01-2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [36]:
# Count missing values in each column
df.isnull().sum()

Sr No                   0
Date dd/mm/yyyy         0
Startup Name            0
Industry Vertical     171
SubVertical           936
City  Location        180
Investors Name         24
InvestmentnType         4
Amount in USD         960
Remarks              2625
dtype: int64

In [37]:
# Rename columns for easier access
df.rename(columns={
    'Date dd/mm/yyyy': 'date',
    'Startup Name': 'startup_name',
    'Industry Vertical': 'industry',
    'SubVertical': 'sub_vertical',
    'City  Location': 'city',
    'Investors Name': 'investors',
    'InvestmentnType': 'investment_type',
    'Amount in USD': 'amount_usd'
}, inplace=True)

df.columns  # confirm new names

Index(['Sr No', 'date', 'startup_name', 'industry', 'sub_vertical', 'city',
       'investors', 'investment_type', 'amount_usd', 'Remarks'],
      dtype='object')

In [38]:
# Fill missing text columns with 'Unknown'
df['industry'].fillna('Unknown', inplace=True)
df['sub_vertical'].fillna('Unknown', inplace=True)
df['city'].fillna('Unknown', inplace=True)
df['investors'].fillna('Unknown', inplace=True)
df['investment_type'].fillna('Unknown', inplace=True)
# Remove commas from amount column so it can be converted to numeric
df['amount_usd'] = df['amount_usd'].astype(str).str.replace(',', '', regex=False)

# Replace text like 'undisclosed' with NaN since it's not a number
df['amount_usd'] = df['amount_usd'].str.lower().replace('undisclosed', pd.NA)

# Now convert to numeric — non-convertible values become NaN
df['amount_usd'] = pd.to_numeric(df['amount_usd'], errors='coerce')


# Fill missing amount with 0
df['amount_usd'].fillna(0, inplace=True)

# confirm no missing values remain
df.isnull().sum()

/tmp/ipykernel_510/3824183840.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['industry'].fillna('Unknown', inplace=True)
/tmp/ipykernel_510/3824183840.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sub_vertical'].fillna('Unknown', inplace=True)
/tmp/ipykernel_510/3824183840.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna('Unknown', inplace=True)
/tmp/ipykernel_510/3824183840.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['investors'].fillna('Unknown', inplace=True)
/tmp/ipykernel_510/3824183840.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['investment_type'].fillna('Unknown', inplace=True)
/tmp/ipykernel_510/3824183840.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['amount_usd'].fillna(0, inplace=True)

Sr No                 0
date                  0
startup_name          0
industry              0
sub_vertical          0
city                  0
investors             0
investment_type       0
amount_usd            0
Remarks            2625
dtype: int64

In [39]:
# Remove exact duplicate rows

df.drop_duplicates(inplace=True)
print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 3044

In [40]:
# strip() removes spaces
# title() used to capitalize first letter of each word
# lower() for investment type to keep it uniform

df['startup_name'] = df['startup_name'].str.strip().str.title()
df['industry'] = df['industry'].str.strip().str.title()
df['sub_vertical'] = df['sub_vertical'].str.strip().str.title()
df['city'] = df['city'].str.strip().str.title()
df['investors'] = df['investors'].str.strip()
df['investment_type'] = df['investment_type'].str.strip().str.lower()

df.head()

,Sr No,date,startup_name,industry,sub_vertical,city,investors,investment_type,amount_usd,Remarks
0,1,09-01-2020,Byju’S,E-Tech,E-Learning,Bengaluru,Tiger Global Management,private equity round,200000000.0,NaN
1,2,13-01-2020,Shuttl,Transportation,App Based Shuttle Service,Gurgaon,Susquehanna Growth Equity,series c,8048394.0,NaN
2,3,09-01-2020,Mamaearth,E-Commerce,Retailer Of Baby And Toddler Products,Bengaluru,Sequoia Capital India,series b,18358860.0,NaN
3,4,02-01-2020,Https://Www.Wealthbucket.In/,Fintech,Online Investment,New Delhi,Vinod Khatumal,pre-series a,3000000.0,NaN
4,5,02-01-2020,Fashor,Fashion And Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,seed round,1800000.0,NaN

In [41]:
# Convert date column to datetime format
df['date'] = pd.to_datetime(df['date'], dayfirst=True, errors='coerce')

# Convert amount_usd column to numeric
df['amount_usd'] = pd.to_numeric(df['amount_usd'], errors='coerce').fillna(0)

df.dtypes  # confirm types

Sr No                       int64
date               datetime64[ns]
startup_name               object
industry                   object
sub_vertical               object
city                       object
investors                  object
investment_type            object
amount_usd                float64
Remarks                    object
dtype: object

In [42]:
# Extract year from date — useful for year-wise trend analysis
df['funding_year'] = df['date'].dt.year
df[['date', 'funding_year']].head()

        date  funding_year
0 2020-01-09        2020.0
1 2020-01-13        2020.0
2 2020-01-09        2020.0
3 2020-01-02        2020.0
4 2020-01-02        2020.0

In [43]:
# Save the final cleaned dataframe to a new CSV file
df.to_csv('cleaned_dataset.csv', index=False)
print("Cleaned dataset saved successfully!")
print("Final shape:", df.shape)

Cleaned dataset saved successfully!
Final shape: (3044, 11)

In [44]:
from google.colab import files
files.download('cleaned_dataset.csv')